name: fenicsxconcrete
channels:
  - conda-forge
dependencies:
  # runtime
  - fenics-dolfinx
  - pint
  - matplotlib
  - python-gmsh
  - meshio
  # tests
  - pytest
  - coverage
  - toml
  # docs
  - sphinx
  - myst-parser
  - sphinx_rtd_theme
  # formatting
  - black
  - isort
  - pip
  - pip:
      - -e .
